Fix __traceback_supplement__ for Plone 3.0
Near as I can tell PageTemplateTracebackSupplement still expects two
arguments in Zope 2.10.  I couldn't find any test coverage for
patch_cmf but I was getting ExceptionFormatter errors in tests in
other code that use CacheSetup:

Traceback (most recent call last):
  File ".../lib/python/zExceptions/ExceptionFormatter.py", line 156, in formatLine
    supp = factory(*args)
TypeError: __init__() takes exactly 3 arguments (2 given)